import QtQuick
import qs.Commons

// The Omanote mark drawn natively as pixel runs on a 16×16 grid (generated by
// tools/gen-icons.py): a 13-cell pencil in 1-pixel lines, like the Omarchy logo,
// sized to sit level with the other bar icons. Plain Rectangles keep it crisp in tiny bar slots and let it take
// the bar colour.
Item {
  id: root

  property real iconSize: Style.bar.iconCanvas
  property color color: Color.foreground

  readonly property var art: [
    "................",
    "................",
    "...........X....",
    "..........X.X...",
    ".........X...X..",
    "........X.X.X...",
    ".......X...X....",
    "......X...X.....",
    ".....X...X......",
    "....X...X.......",
    "...X.X.X........",
    "..X...X.........",
    "..XX.X..........",
    "..XXX...........",
    "................",
    "................"
  ]
  readonly property real cell: iconSize / 16
  readonly property var runs: {
    var out = []
    for (var y = 0; y < art.length; y++) {
      var row = art[y]
      var x = 0
      while (x < row.length) {
        if (row[x] !== "X") { x++; continue }
        var n = 1
        while (row[x + n] === "X") n++
        out.push({ x: x, y: y, w: n })
        x += n
      }
    }
    return out
  }

  width: iconSize
  height: iconSize
  implicitWidth: iconSize
  implicitHeight: iconSize

  Repeater {
    model: root.runs
    Rectangle {
      required property var modelData
      x: Math.round(modelData.x * root.cell)
      y: Math.round(modelData.y * root.cell)
      width: Math.round((modelData.x + modelData.w) * root.cell) - x
      height: Math.round((modelData.y + 1) * root.cell) - y
      color: root.color
      antialiasing: false
    }
  }
}
