// Pixel icons in the Omarchy look, after the logo in the Omarchy bar: 1-pixel
// outlines on a 16×16 grid, square corners. They use currentColor, so they
// follow the theme. Used both in Svelte ({@html}) and in CodeMirror widgets.
//
// Each icon is drawn as rows of text: "X" is a filled cell, anything else empty.

const SIZE = 16;

function pixel(art: string): string {
  const rows = art.trim().split("\n").map((r) => r.trim());
  let d = "";
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; ) {
      if (row[x] !== "X") {
        x++;
        continue;
      }
      let n = 1;
      while (row[x + n] === "X") n++;
      d += `M${x} ${y}h${n}v1h-${n}z`;
      x += n;
    }
  });
  return `<svg class="ico" viewBox="0 0 ${SIZE} ${SIZE}" width="1em" height="1em" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true"><path d="${d}"/></svg>`;
}

/**
 * Sets `--ico-s` / `--ico-l` (small and large icon sizes, in CSS px) so each grid
 * cell covers a whole number of screen pixels: 1-pixel lines stay sharp at any
 * display scale (1.25 on many Linux laptops, 2 on Retina).
 */
export function fitIconsToScreen() {
  const apply = () => {
    const dpr = window.devicePixelRatio || 1;
    const size = (target: number) => (SIZE * Math.max(1, Math.round((target * dpr) / SIZE))) / dpr;
    const root = document.documentElement.style;
    root.setProperty("--ico-s", `${size(15)}px`);
    root.setProperty("--ico-l", `${size(22)}px`);
    matchMedia(`(resolution: ${dpr}dppx)`).addEventListener("change", apply, { once: true });
  };
  apply();
}

export const icons = {
  /** Folder tree panel. */
  menu: pixel(`
    ................
    ................
    ................
    .XXXXXXXXXXXXXX.
    .X..............
    .X..............
    .X..............
    .XX.XXXXXXXXXXX.
    .X..............
    .X..............
    .X..............
    .XX.XXXXXXXX....
    ................
    ................
    ................
    ................`),
  /** New note. */
  plus: pixel(`
    ................
    ................
    .......X........
    .......X........
    .......X........
    .......X........
    .......X........
    ..XXXXXXXXXXX...
    .......X........
    .......X........
    .......X........
    .......X........
    .......X........
    ................
    ................
    ................`),
  /** Close a panel or remove something. */
  close: pixel(`
    ................
    ................
    ..X.........X...
    ...X.......X....
    ....X.....X.....
    .....X...X......
    ......X.X.......
    .......X........
    ......X.X.......
    .....X...X......
    ....X.....X.....
    ...X.......X....
    ..X.........X...
    ................
    ................
    ................`),
  settings: pixel(`
    .....XXXXX......
    .XX..X...X..XX..
    .X.XXX...XXX.X..
    .XX.........XX..
    ..X.........X...
    XXX.........XXX.
    X.....XXX.....X.
    X.....X.X.....X.
    X.....XXX.....X.
    XXX.........XXX.
    ..X.........X...
    .XX.........XX..
    .X.XXX...XXX.X..
    .XX..X...X..XX..
    .....XXXXX......
    ................`),
  search: pixel(`
    .XXXXXXXX.......
    XX......XX......
    X........X......
    X........X......
    X........X......
    X........X......
    X........X......
    X........X......
    XX......XX......
    .XXXXXXXXXX.....
    ..........XX....
    ...........XX...
    ............XX..
    .............XX.
    ..............X.
    ................`),
  /** Keep the window on top. */
  pin: pixel(`
    ...XXXXXXXXX....
    ...X.......X....
    ....X.....X.....
    ....X.....X.....
    ....X.....X.....
    ..XX.......XX...
    .X...........X..
    .XXXXXXXXXXXXX..
    .......X........
    .......X........
    .......X........
    .......X........
    .......X........
    .......X........
    .......X........
    ................`),
  /** OCR of a screen region. */
  capture: pixel(`
    XXXX.......XXXX.
    X.............X.
    X.............X.
    X.............X.
    ................
    ................
    .......X........
    ......XXX.......
    .......X........
    ................
    ................
    X.............X.
    X.............X.
    X.............X.
    XXXX.......XXXX.
    ................`),
  /** Sync status: one block, coloured by state. */
  sync: pixel(`
    ................
    ................
    ................
    ................
    ................
    .....XXXXX......
    .....XXXXX......
    .....XXXXX......
    .....XXXXX......
    .....XXXXX......
    ................
    ................
    ................
    ................
    ................
    ................`),
  /** Folder options. */
  more: pixel(`
    ................
    ................
    ................
    ................
    ................
    ................
    .XX...XX...XX...
    .XX...XX...XX...
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................`),
  prev: pixel(`
    ................
    ................
    .........XX.....
    ........XX......
    .......XX.......
    ......XX........
    .....XX.........
    ....XX..........
    .....XX.........
    ......XX........
    .......XX.......
    ........XX......
    .........XX.....
    ................
    ................
    ................`),
  next: pixel(`
    ................
    ................
    ....XX..........
    .....XX.........
    ......XX........
    .......XX.......
    ........XX......
    .........XX.....
    ........XX......
    .......XX.......
    ......XX........
    .....XX.........
    ....XX..........
    ................
    ................
    ................`),
  /** Collapsed tree branch. */
  expand: pixel(`
    ................
    ................
    ....X...........
    ....XX..........
    ....X.X.........
    ....X..X........
    ....X...X.......
    ....X....X......
    ....X...X.......
    ....X..X........
    ....X.X.........
    ....XX..........
    ....X...........
    ................
    ................
    ................`),
  /** Open tree branch. */
  collapse: pixel(`
    ................
    ................
    ................
    ................
    ..XXXXXXXXXXX...
    ...X.......X....
    ....X.....X.....
    .....X...X......
    ......X.X.......
    .......X........
    ................
    ................
    ................
    ................
    ................
    ................`),
  /** Conflicting copy of a note. */
  warn: pixel(`
    ................
    .......X........
    ......X.X.......
    ......X.X.......
    ......X.X.......
    .....X.X.X......
    ....X..X..X.....
    ....X..X..X.....
    ....X..X..X.....
    ...X...X...X....
    ..X.........X...
    ..X....X....X...
    ..X.........X...
    .XXXXXXXXXXXXX..
    ................
    ................`),
  /** Picture: frame, sun, mountains. */
  image: pixel(`
    ................
    XXXXXXXXXXXXXXX.
    X.............X.
    X........XXX..X.
    X........X.X..X.
    X........XXX..X.
    X.............X.
    X.............X.
    X....X........X.
    X...X.X...X...X.
    X..X...X.X.X..X.
    X.X.....X...X.X.
    XX...........XX.
    XXXXXXXXXXXXXXX.
    ................
    ................`),
  /** Text from an image: scan corners around lines of text. */
  ocr: pixel(`
    XXX.........XXX.
    X.............X.
    X.............X.
    ................
    ...XXXXXXXXX....
    ................
    ................
    ...XXXXXXXXX....
    ................
    ................
    ...XXXXXX.......
    ................
    X.............X.
    X.............X.
    XXX.........XXX.
    ................`),
  /** Encrypted note. */
  lock: pixel(`
    ................
    ....XXXXXXX.....
    ...X.......X....
    ...X.......X....
    ...X.......X....
    ...X.......X....
    .XXXXXXXXXXXXX..
    .X...........X..
    .X...........X..
    .X.....X.....X..
    .X.....X.....X..
    .X.....X.....X..
    .X...........X..
    .X...........X..
    .XXXXXXXXXXXXX..
    ................`),
  /** New folder. */
  folderAdd: pixel(`
    ................
    XXXXXX..........
    X.....X.........
    X......XXXXXXXX.
    X.............X.
    X.............X.
    X......X......X.
    X......X......X.
    X....XXXXX....X.
    X......X......X.
    X......X......X.
    X.............X.
    X.............X.
    XXXXXXXXXXXXXXX.
    ................
    ................`),
  /** A note in the tree. */
  note: pixel(`
    ................
    ................
    ................
    ................
    ................
    ................
    .......X........
    ......XXX.......
    .......X........
    ................
    ................
    ................
    ................
    ................
    ................
    ................`),
};
