#!/usr/bin/env python3
"""Regenerates app/src/themes.css from the Omarchy theme palettes.

Usage: python3 tools/gen-themes.py            (downloads from the Omarchy repo)
       python3 tools/gen-themes.py themes.json (uses a local dump)

On Omarchy itself the app follows the system theme at runtime instead; these
bundled copies are for macOS, Windows, iOS and Android.
"""
import json, re, subprocess, sys, pathlib

REPO = "https://api.github.com/repositories/994093166/contents/themes"
ORDER_FIRST = ["tokyo-night", "catppuccin", "gruvbox", "everforest", "nord", "kanagawa", "rose-pine", "matte-black"]


def curl(url: str) -> str:
    return subprocess.run(["curl", "-sL", "--max-time", "20", url], capture_output=True, text=True).stdout


def download() -> dict:
    out = {}
    for entry in json.loads(curl(REPO)):
        meta = json.loads(curl(f"{REPO}/{entry['name']}/colors.toml") or "{}")
        if "download_url" not in meta:
            continue
        colors = dict(re.findall(r'(?m)^(\w+)\s*=\s*"([^"]+)"', curl(meta["download_url"])))
        if "background" in colors and "accent" in colors:
            out[entry["name"]] = colors
    return out


def block(name: str, c: dict, selector: str) -> str:
    return f"""{selector} {{
  color-scheme: {c.get('mode', 'dark')};
  --bg: {c['background']};
  --bar: {c.get('dark_background', c['background'])};
  --bg-elev: {c.get('lighter_background', c['background'])};
  --panel: {c.get('selection', c['background'])};
  --text: {c['foreground']};
  --muted: {c.get('dark_foreground', c.get('muted', c['foreground']))};
  --line: {c.get('selection', c.get('muted', c['foreground']))};
  --accent: {c['accent']};
  --result: {c.get('green', c['accent'])};
  --danger: {c.get('red', c['accent'])};
}}
"""


def main() -> None:
    data = json.load(open(sys.argv[1])) if len(sys.argv) > 1 else download()
    names = [n for n in ORDER_FIRST if n in data] + sorted(n for n in data if n not in ORDER_FIRST)
    css = ["/* Generated by tools/gen-themes.py from the Omarchy themes - do not edit by hand. */\n"]
    css.append(block("tokyo-night", data["tokyo-night"], ":root"))
    for n in names:
        css.append(block(n, data[n], f':root[data-theme="{n}"]'))
    css.append("/* Theme list for the picker: " + ",".join(names) + " */\n")
    path = pathlib.Path(__file__).parent.parent / "app/src/themes.css"
    path.write_text("\n".join(css))
    json.dump({n: {"mode": data[n].get("mode", "dark"), "accent": data[n]["accent"], "bg": data[n]["background"]} for n in names},
              open(path.parent / "lib/themes.json", "w"), indent=1)
    print(f"{len(names)} themes → {path}")


main()
